# Generated by Django 2.2.4 on 2019-10-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationQueue',
            fields=[
                ('task_uuid',
                 models.UUIDField(primary_key=True, serialize=False)),
                ('asset_uuid', models.UUIDField()),
                ('method', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Validation queue',
                'verbose_name_plural': 'Validation queue',
                'db_table': 'validation_queue',
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(
                    choices=[('FIAT', 'FIAT'), ('COIN', 'COIN'),
                             ('TOKEN', 'TOKEN')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.UUIDField()),
                ('symbol', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=42, null=True)),
                ('platform', models.UUIDField(blank=True, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('is_valid',
                 models.BooleanField(verbose_name='Overall validation result')),
                ('validation_results', models.TextField(blank=True, null=True)),
                ('validation_time', models.DateTimeField(
                    verbose_name='What time did the result come')),
                ('result_message', models.TextField(blank=True, null=True,
                                                    verbose_name='Error or information message from validator')),
                ('user', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL,
                                           verbose_name='Who requested validation')),
            ],
            options={
                'verbose_name': 'Asset history',
                'verbose_name_plural': 'Asset history',
                'db_table': 'asset_history',
            },
        ),
    ]
