# Generated by Django 2.2.4 on 2019-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
