# Generated by Django 2.2.4 on 2020-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_auto_20191115_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistory',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('applied', 'Applied'), ('discarded', 'Discarded')], default='applied', max_length=100),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='task_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='validation_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='is_valid',
            field=models.BooleanField(null=True, verbose_name='Overall validation result'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='validation_time',
            field=models.DateTimeField(null=True, verbose_name='What time did the result come'),
        ),
    ]
